export const initialStorage = {
    fromAddress: "",
    toAddress: "",
    distance: 0,
    starting_point: {
        icon: "",
        title: "",
    },
    selected_items: [],
    pickup_date: {
        date: "",
        day: "",
        cost: "",
    },
    pickup_time: {
        time: "",
        cost: "",
    },
    pickup_floor: {
        cost: "",
        desc: "",
        icon: "",
        title: "",
    },
    request_assistance: {
        cost: "",
        icon: "",
        title: "",
        descriptions: "",
        "0-50km": "",
        "50-100km": "",
        "100-200km": "",
        "201-300km": "",
    },
    delivery_time: {
        time: "",
        cost: "",
    },
    delivery_floor: {
        cost: "",
        desc: "",
        icon: "",
        title: "",
    },
    pickup_contact: {
        name: "",
        email: "",
        phone: "",
        address: "",
    },
    delivery_contact: {
        name: "",
        email: "",
        phone: "",
        address: "",
    },
    personal_details: {
        firstName: "",
        lastName: "",
        email: "",
        phoneNumber: "",
        companyName: "",
        chamberOfCommerce: "",
        vatNumber: "",
        streetAddress: "",
        postalCode: "",
        areaCode: "",
        newsletter: false,
        agreeTerms: false,
        agreePrivacy: false,
    },
    auction_details: {
        auction_name: "",
        image: "",
    },
    transportPrice: 0,
    total_price: 0,
};
